FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 3000

CMD sh -c "sleep 10 && npx prisma migrate deploy && npx prisma db seed && npm run start:dev"