-- AlterTable
ALTER TABLE `Payment` ADD COLUMN `status` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `User` ADD COLUMN `role` ENUM('REGISTRATION', 'AUTHORIZATION', 'ADMIN') NOT NULL DEFAULT 'REGISTRATION';
